// Code generated by syncer vendor; DO NOT EDIT
//go:build syncer

// THIS FILE IS AUTOGENERATED BY SYNCER DO NOT EDIT

package main

import (
	_ "github.com/getsyncer/public-sync-modules/opensourcegolib"
	"github.com/getsyncer/syncer-core/syncerexec"
)

func main() {
	syncerexec.FromCli(syncerexec.DefaultFxOptions())
}
